#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright 2013 Xavier Bruhiere
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


'''pencil

Usage:
    pencil --version
    pencil -h | --help
    pencil login [--user=<name>] [--password=<mdp>] [--host=<ip>] [--port=<port>]
    pencil up --app=<name> [--config=<file> | --key=<value>] [--host=<ip>] [--port=<port>]
    pencil configure --app=<name> (--config=<file> | --key=<value>) [--host=<ip>] [--port=<port>]
    pencil inspect --app=<name> [--host=<ip>] [--port=<port>]

Options:
    --version               Show version.
    -h --help               Show this screen.
    --app <app>             Run the command against the app named <app>.
    --config <file>         YAML style configuration file.
    --key <value>           Single parameter to set.
    --host <ip>             Centralized configuration manager address [default: 127.0.0.1].
    --port <port>           Centralized configuration manager port [default: 4001].
    --user <name>           Username for api login
    --password <mdp>        Password for api login
'''

from docopt import docopt
#import sys
from libpencil import Pencil
import utils


def main(args):
    '''
    Main entry for final user
    Use arguments parsed by docopt
    '''

    c = Pencil(project=args['--app'], host=args['--host'], port=args['--port'],
               follow_leader=True, autostart=True)

    if args['configure']:
        if args['--config']:
            configuration = utils.load_yaml(args['--config'])

            for k, v in configuration.items():
                if k == 'cells':
                    services = []
                    for cell in configuration['cells']:
                        services.append(cell['charm'])
                        for k_cell, v_cell in cell.items():
                            print(c.configure(
                                c.charmpath(cell['charm']), k_cell, v_cell))
                    print(c.configure(
                        c.projectpath(), 'services', ','.join(services)))
                else:
                    print(c.configure(c.projectpath(), k, v))

        if args['--key']:
            keyvalue = args['--key'].split(':')
            print(c.configure(c.projectpath(), keyvalue[0], keyvalue[1]))

    elif args['up']:
        #TODO: Provided config settings
        if args['--config'] or args['--key']:
            raise(NotImplementedError)
        print(c.up())

    elif args['login']:
        print(c.login(args['--user'], args['--password']))

    elif args['inspect']:
        raise(NotImplementedError)

if __name__ == '__main__':
    args = docopt(__doc__, version='Dokku client, pencil v0.1.2')

    #NOTE For dev mode I wan to see what went wrong
    #try:
    main(args)
    #except:
    #TODO Custom error handler
    #sys.exit("** Error running pencil...")
