web: GOMAXPROCS=2 hivy --listen 127.0.0.1:8888 --verbose --profile
config: etcd -c 0.0.0.0:4001 -n master -d .conf -v && while true; do sleep 10000; done
queues: redis-server && while true; do sleep 10000; done
worker: echo "worker listening" && sleep 5 && worker -queues fork -interval 5
proxy: DEBUG=* boxcars -port=8080 proxy-routes.json
monitor: serf agent -role=origin -log-level=debug -event-handler "member-join=../scripts/update_network.sh"
