#!/bin/bash
#or put it near etcd...
ETCDPATH="/home/supercoin/go/src/src/github.com/coreos/etcd"
case $1 in
	run)
		INSTANCE_NAME=$2
		echo $($ETCDPATH/etcd -d $INSTANCE_NAME -n $INSTANCE_NAME) > logs

	;;
	stop)
		INSTANCE_NAME=$2
		echo $(ps aux | grep "\-d\ $INSTANCE_NAME \-n\ $INSTANCE_NAME" | grep -v "grep" | awk '{print $2}' | xargs kill -9) > logs
	;;
	init)
		SERV_NAME=$2
		PORT=$3
		IP=$4

		if [ -n $PORT ]; then
			sed -i s/4001/$PORT/g $SERV_NAME/info
		fi
		if [ -n $IP ]; then
			sed -i s/127\.0\.0\.1/$IP/g $SERV_NAME/info
		fi
	;;
esac

