#! /bin/bash

IP=192.168.0.12
PORT=8081
PATH_KEY=$2
VALUE=$3
PREFIX=api/conf

# https://github.com/coreos/etcd
if [ "$1" == "get" ]; then
    curl -L http://$IP:$PORT/$PREFIX/$PATH_KEY | underscore print --color 
elif [ "$1" == "set" ]; then
    curl -L http://$IP:$PORT/$PREFIX/$PATH_KEY -d value="$VALUE" | underscore print --color 
else
    echo "Unknown command, use set or get."
fi
