#! /bin/bash

IP=127.0.0.1
PORT=8080
USER=xav
PASS=boss
MAJOR_VERSION=v0

METHOD=$1
REQUEST=$2

# https://github.com/jkbr/httpie
http --auth $USER:$PASS $METHOD http://$IP:$PORT/$MAJOR_VERSION/actions/$REQUEST
